### ISSUE TITLE
debian9.1で動作しません

### ISSUE THREAD

**Issue by so5** [ifritJP/lctags#1]
dockerのdebian9.1のイメージを使って環境を用意し、次の手順でインストールしてみましたが、DBを生成する時点でエラーが発生しました。

`>`はホストOSでの`#`はdocker内での操作を示します。
```
>docker run -it --rm debian:9.1 /bin/bash
# apt update
# apt install git make python sudo curl unzip
# git clone https://github.com/ifritJP/lctags.git
# cd lctags
# make build_for_apt
# make install
```

エラー内容
```
# lctags init .
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
please set clang inc-path at getClangIncPath() in /lctags/lctags.conf, and retry init.
```

**Comment by ifritJP** [comment]
レポートありがとうございます。

これは、lctags で利用している libclang が、
clang の include ディレクトリを認識できていないことを示します。

lctags init を実行したディレクトリに生成される lctags.conf ファイルの
config:getClangIncPath() を編集することで
clang の include ディレクトリを指定できます。

次を実行すると今回の件は解消できます。

```
# sed -i.bak 's@return nil -- clang include path@return "/usr/lib/llvm-3.8/lib/clang/3.8.1/include"@' /usr/local/share/lua/5.3/lctags/_lctags.conf
```

これにより /usr/local/share/lua/5.3/lctags/_lctags.conf 内の
getClangIncPath() が次のように変更されます。

```
function config:getClangIncPath()
   -- return "/usr/lib/llvm/lib/clang/include"
   return "/usr/lib/llvm-3.8/lib/clang/3.8.1/include"
end
```

lctags init . を実行したディレクトリには lctags.conf が作成されています。
これを一旦削除してから、再度 lctags init . してください。

```
# rm lctags.conf
# lctags init .
```

この時の lctags init . でも同様のエラーが出力されますが、
lctags build 等は正常に動作します。

確認をお願いします。

**Comment by so5** [comment]
さっそくのご対応ありがとうございます。

たしかに、lctags.confのパスを書き換えることで、`lctags build`は正常に動作するようになりました。
